// variant2-react/src/components/Header.js
import React, { useState, useEffect } from 'react';

const Header = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  const scrollToSection = (sectionId) => {
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    setIsMenuOpen(false);
  };

  return (
    <header className={`header ${isScrolled ? 'scrolled' : ''}`}>
      <div className="nav-container">
        <div className="logo">
          <h1>IMR</h1>
          <span>Industrieverwertung</span>
        </div>
        <ul className={`nav-menu ${isMenuOpen ? 'active' : ''}`}>
          <li><a onClick={() => scrollToSection('firmenaufloesung')}>Firmenauflösung</a></li>
          <li><a onClick={() => scrollToSection('betriebsaufloesung')}>Betriebsauflösung</a></li>
          <li><a onClick={() => scrollToSection('industrieverwertung')}>Industrieverwertung</a></li>
          <li><a onClick={() => scrollToSection('kontakt')}>Kontakt</a></li>
        </ul>
        <div className={`hamburger ${isMenuOpen ? 'active' : ''}`} onClick={toggleMenu}>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </header>
  );
};

export default Header;

// variant3-vue/src/components/Header.vue
<template>
  <header :class="['header', { scrolled: isScrolled }]">
    <div class="nav-container">
      <div class="logo">
        <h1>IMR</h1>
        <span>Industrieverwertung</span>
      </div>
      <ul :class="['nav-menu', { active: isMenuOpen }]">
        <li><a @click="scrollToSection('firmenaufloesung')">Firmenauflösung</a></li>
        <li><a @click="scrollToSection('betriebsaufloesung')">Betriebsauflösung</a></li>
        <li><a @click="scrollToSection('industrieverwertung')">Industrieverwertung</a></li>
        <li><a @click="scrollToSection('kontakt')">Kontakt</a></li>
      </ul>
      <div :class="['hamburger', { active: isMenuOpen }]" @click="toggleMenu">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </header>
</template>

<script>
export default {
  name: 'Header',
  data() {
    return {
      isMenuOpen: false,
      isScrolled: false
    }
  },
  mounted() {
    window.addEventListener('scroll', this.handleScroll)
  },
  beforeUnmount() {
    window.removeEventListener('scroll', this.handleScroll)
  },
  methods: {
    toggleMenu() {
      this.isMenuOpen = !this.isMenuOpen
    },
    handleScroll() {
      this.isScrolled = window.scrollY > 50
    },
    scrollToSection(sectionId) {
      const element = document.getElementById(sectionId)
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' })
      }
      this.isMenuOpen = false
    }
  }
}
</script>
