// variant2-react/src/components/Services.js
import React from 'react';

const Services = () => {
  const services = [
    {
      title: 'Maschinen & Fahrzeuge',
      description: 'Professionelle Verwertung von Industriemaschinen und Fahrzeugen'
    },
    {
      title: 'Verwertung & Recycling',
      description: 'Nachhaltige Verwertung und umweltgerechtes Recycling'
    },
    {
      title: 'Demontage & Abbrüche',
      description: 'Fachgerechte Demontage und Abbrucharbeiten'
    }
  ];

  return (
    <section className="services">
      <div className="container">
        <h3>Unsere Leistungen</h3>
        <div className="services-grid">
          {services.map((service, index) => (
            <div key={index} className="service-card">
              <h4>{service.title}</h4>
              <p>{service.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Services;

// variant3-vue/src/components/Services.vue
<template>
  <section class="services">
    <div class="container">
      <h3>Unsere Leistungen</h3>
      <div class="services-grid">
        <div v-for="(service, index) in services" :key="index" class="service-card">
          <h4>{{ service.title }}</h4>
          <p>{{ service.description }}</p>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Services',
  data() {
    return {
      services: [
        {
          title: 'Maschinen & Fahrzeuge',
          description: 'Professionelle Verwertung von Industriemaschinen und Fahrzeugen'
        },
        {
          title: 'Verwertung & Recycling',
          description: 'Nachhaltige Verwertung und umweltgerechtes Recycling'
        },
        {
          title: 'Demontage & Abbrüche',
          description: 'Fachgerechte Demontage und Abbrucharbeiten'
        }
      ]
    }
  }
}
</script>
